services:
  mqtt-net-power-calculator:
    image: python:3.12-slim
    container_name: mqtt-net-power-calculator
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mqtt_net_power_calculator.py:/app/calculator.py
      - ./config.py:/app/config.py
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install -r requirements.txt && python calculator.py"
